version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  dynamodb:
    image: amazon/dynamodb-local

  web:
    build: .
    command: /bin/bash
    env_file: .env
    tty: true
    volumes:
      - .:/inbox
    ports:
      - "3000:3000"
    depends_on:
      - db
      - dynamodb
