version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: /bin/bash
    tty: true
    volumes:
      - .:/inbox
    ports:
      - "3000:3000"
    depends_on:
      - db
