apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: inbox-ms
spec:
  ports:
    - port: 5432
  selector:
    app: inbox-ms
    tier: postgres

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres
  labels:
    app: inbox-ms
spec:
  replicas: 1
  selector:
    app: inbox-ms
    tier: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: inbox-ms
        tier: postgres
    spec:
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
      - name: postgres
        image: postgres:9.6-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-user
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password
        - name: POSTGRES_DB
          value: rails-kube-demo_production
        - name: PGDATA
          value: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-pv
