default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_URL") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>
  pool: 5

development:
  <<: *default
  database: inbox_development

test:
  <<: *default
  database: inbox_test

production:
  <<: *default
  database: inbox_production
